name: Verify PR

on:
    pull_request:
        branches: [main]

jobs:
  verify-pr:
    runs-on: xcode-27

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run tests
        run: |
          xcodebuild test \
            -project Shifts.xcodeproj \
            -scheme Shifts \
            -parallel-testing-enabled NO \
            -destination 'platform=iOS Simulator,arch=arm64,name=iPhone 18'
